version: '3'

services:
  sesame-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    container_name: ${APP_NAME:-sesame-daemon}
    volumes:
      - ./:/data
    networks: ['dev']
    environment:
      - NODE_ENV=development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: yarn start:debug

networks:
  dev:
    external: true
