
name: 'config1'
description: 'Config1 backend for tests'
active: 0
actions:
  CHANGEPWD:
      exec: "exemple.sh"
      onError: 'continue'
  RESETPWD:
      exec: "exemple.sh
      onError: 'continue'
  ADDIDENT:
      exec: 'exemple.sh'
      onError: 'continue'
  UPDATEIDENT:
      exec: 'exemple.sh'
      onError: 'continue'
  DELIDENT:
      exec: 'exemple.sh'
      onError: 'continue'
  PING:
      exec: 'exemple.sh'
      onError: 'continue'

