
name: 'AD'
description: 'Backend for AD'
active: 0
actions:
  CHANGEPWD:
      script: "changepasswd"
      onError: 'stop'
  RESETPWD:
      script: "resetpasswd"
      onError: 'stop'
  IDENTITY_CREATE:
      script: 'dummy.sh'
  IDENTITY_UPDATE:
      script: 'dummy.sh'
  DELIDENT:
      script: 'dummy.sh'
  PING:
      script: 'ping.sh'
