_version: 1

name: 'AD'
description: 'Backend for AD'
active: false
actions:
  IDENTITY_PASSWORD_CHANGE:
    script: "changepasswd"
    onError: 'stop'
  IDENTITY_PASSWORD_RESET:
    script: "resetpasswd"
    onError: 'stop'
