name: Build and release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: yarn --frozen-lockfile
      - run: npm install --global pkg
      - name: Build
        run: pkg index.js --output sesame-daemon --targets linux,macos,win
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sesame-daemon-linux
            sesame-daemon-macos
            sesame-daemon-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
