name: Build and release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn --frozen-lockfile
      - run: npm install --global pkg
      - run: yarn build
#      - run: curl -sf https://gobinaries.com/tj/node-prune | sh
#      - run: node-prune
      - name: Build
        run: pkg dist/main.js -o sesame-daemon --targets linux,macos,win -C Brotli
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sesame-daemon-linux
            sesame-daemon-macos
            sesame-daemon-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
