name: Release

on:
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'La version a incrémenter (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'
      build_docker_image:
        description: "Construire l'image docker ?"
        required: true
        default: true
        type: boolean
      latest:
        description: "Tagger l'image docker avec le tag 'latest' ?"
        required: true
        default: true
        type: boolean

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Build docker
        uses: Libertech-FR/lt-actions/release@main
        with:
          version_increment: ${{ github.event.inputs.version_increment }}
          build_docker_image: ${{ github.event.inputs.build_docker_image }}
          latest: ${{ github.event.inputs.latest }}
          repository: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          access_token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional parameters, thoses are default values :
          registry: 'ghcr.io'
          context: .

  build-pkg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install -g yarn
      - run: yarn --frozen-lockfile
      - run: npm install --global pkg
      - run: yarn build
#      - run: curl -sf https://gobinaries.com/tj/node-prune | sh
#      - run: node-prune

      - name: Build
        run: pkg dist/main.js -o sesame-daemon --targets linux,macos,win -C Brotli

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sesame-daemon-linux
          path: sesame-daemon-linux

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: sesame-daemon-linux

      - name: Init deb package
        run: |
          mkdir -p .debpkg/usr/bin
          cp sesame-daemon-linux .debpkg/usr/bin/sesame-daemon
          mkdir -p .debpkg/var/lib/sesame-daemon/backends
          cp -r ./backends.example .debpkg/var/lib/sesame-daemon/backends
          chmod +x .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postrm

      - name: Set Package Version
        run: |
          echo "PACKAGE_VERSION=$(cat package.json | jq .version -r)" >> $GITHUB_ENV


      - name: Create deb package
        uses: jiro4989/build-deb-action@v3
        with:
          package: sesame-daemon
          package_root: .debpkg
          maintainer: Libertech-FR
          version: ${{ env.PACKAGE_VERSION }} # ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          desc: 'Sesame Daemon'
